1. Import libraries

In [15]:
import pandas as pd 
import numpy as np 

import matplotlib.pyplot as plt 
import seaborn as sns

2. Load datasets

In [19]:
sessions = pd.read_csv('../../data/website_sessions.csv')
pageviews = pd.read_csv('../../data/website_pageviews.csv')
orders = pd.read_csv('../../data/orders.csv')
order_items = pd.read_csv('../../data/order_items.csv')
refunds = pd.read_csv('../../data/order_item_refunds.csv')
products = pd.read_csv('../../data/products.csv')

3. Display shape

In [21]:
pd.DataFrame({
    'sessions': sessions.shape,
    'pageviews': pageviews.shape,
    'orders': orders.shape,
    'order_items': order_items.shape,
    'refunds': refunds.shape,
    'products': products.shape
}).T.rename(columns={0: 'rows', 1: 'columns'})

                rows  columns
sessions      472871        9
pageviews    1188124        4
orders         32313        8
order_items    40025        7
refunds         1731        5
products           4        3

In [22]:
pd.DataFrame({
    "table": [
        "sessions",
        "pageviews",
        "orders",
        "order_items",
        "refunds",
        "products"
    ],
    "rows": [
        sessions.shape[0],
        pageviews.shape[0],
        orders.shape[0],
        order_items.shape[0],
        refunds.shape[0],
        products.shape[0]
    ],
    "columns": [
        sessions.shape[1],
        pageviews.shape[1],
        orders.shape[1],
        order_items.shape[1],
        refunds.shape[1],
        products.shape[1]
    ]
})

         table     rows  columns
0     sessions   472871        9
1    pageviews  1188124        4
2       orders    32313        8
3  order_items    40025        7
4      refunds     1731        5
5     products        4        3

4. Display schema

In [25]:
sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 472871 entries, 0 to 472870
Data columns (total 9 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   website_session_id  472871 non-null  int64
 1   created_at          472871 non-null  object
 2   user_id             472871 non-null  int64
 3   is_repeat_session   472871 non-null  int64
 4   utm_source          389543 non-null  object
 5   utm_campaign        389543 non-null  object
 6   utm_content         389543 non-null  object
 7   device_type         472871 non-null  object
 8   http_referer        432954 non-null  object
dtypes: int64(3), object(6)
memory usage: 32.5+ MB

In [26]:
pageviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1188124 entries, 0 to 1188123
Data columns (total 4 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   website_pageview_id  1188124 non-null  int64
 1   created_at           1188124 non-null  object
 2   website_session_id   1188124 non-null  int64
 3   pageview_url         1188124 non-null  object
dtypes: int64(2), object(2)
memory usage: 36.3+ MB

In [27]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32313 entries, 0 to 32312
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            32313 non-null  int64
 1   created_at          32313 non-null  object
 2   website_session_id  32313 non-null  int64
 3   user_id             32313 non-null  int64
 4   primary_product_id  32313 non-null  int64
 5   items_purchased     32313 non-null  int64
 6   price_usd           32313 non-null  float64
 7   cogs_usd            32313 non-null  float64
dtypes: float64(2), int64(5), object(1)
memory usage: 2.0+ MB

In [28]:
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40025 entries, 0 to 40024
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_item_id    40025 non-null  int64
 1   created_at       40025 non-null  object
 2   order_id         40025 non-null  int64
 3   product_id       40025 non-null  int64
 4   is_primary_item  40025 non-null  int64
 5   price_usd        40025 non-null  float64
 6   cogs_usd         40025 non-null  float64
dtypes: float64(2), int64(4), object(1)
memory usage: 2.1+ MB

In [29]:
refunds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1731 entries, 0 to 1730
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   order_item_refund_id  1731 non-null   int64
 1   created_at            1731 non-null   object
 2   order_item_id         1731 non-null   int64
 3   order_id              1731 non-null   int64
 4   refund_amount_usd     1731 non-null   float64
dtypes: float64(1), int64(3), object(1)
memory usage: 67.7+ KB

In [30]:
products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    4 non-null      int64
 1   created_at    4 non-null      object
 2   product_name  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

5. Numerical Summary

In [34]:
orders[
    [
        'items_purchased',
        'price_usd',
        'cogs_usd',
    ]
].describe()

       items_purchased     price_usd      cogs_usd
count     32313.000000  32313.000000  32313.000000
mean          1.238666     59.991636     22.355406
std           0.426274     17.808771      6.238621
min           1.000000     29.990000      9.490000
25%           1.000000     49.990000     19.490000
50%           1.000000     49.990000     19.490000
75%           1.000000     59.990000     22.490000
max           2.000000    109.980000     41.980000

In [36]:
order_items[
    [
        'price_usd',
        'cogs_usd'
    ]
].describe()

          price_usd      cogs_usd
count  40025.000000  40025.000000
mean      48.432473     18.047976
std        8.012370      3.856821
min       29.990000      9.490000
25%       49.990000     19.490000
50%       49.990000     19.490000
75%       49.990000     19.490000
max       59.990000     22.490000

In [37]:
refunds['refund_amount_usd'].describe()

count    1731.000000
mean       49.300225
std         4.956015
min        29.990000
25%        49.990000
50%        49.990000
75%        49.990000
max        59.990000
Name: refund_amount_usd, dtype: float64

6. Categorical Summary

In [39]:
sessions['utm_source'].fillna('organic/direct').value_counts()

utm_source
gsearch           316035
organic/direct     83328
bsearch            62823
socialbook         10685
Name: count, dtype: int64

In [40]:
sessions['utm_campaign'].fillna('organic/direct').value_counts()

utm_campaign
nonbrand            337615
organic/direct       83328
brand                41243
desktop_targeted      5590
pilot                 5095
Name: count, dtype: int64

In [41]:
sessions['device_type'].value_counts()

device_type
desktop    327027
mobile     145844
Name: count, dtype: int64

In [42]:
pageviews['pageview_url'].value_counts()

pageview_url
/products                      261231
/the-original-mr-fuzzy         162525
/home                          137576
/lander-2                      131170
/cart                           94953
/lander-3                       79000
/lander-5                       68166
/shipping                       64484
/billing-2                      48441
/lander-1                       47574
/thank-you-for-your-order       32313
/the-forever-love-bear          26033
/the-birthday-sugar-panda       19046
/lander-4                        9385
/billing                         3617
/the-hudson-river-mini-bear      2610
Name: count, dtype: int64

In [44]:
products['product_name'].value_counts()

product_name
The Original Mr. Fuzzy        1
The Forever Love Bear         1
The Birthday Sugar Panda      1
The Hudson River Mini bear    1
Name: count, dtype: int64

7. Convert Datetime

In [45]:
sessions['created_at'] = pd.to_datetime(sessions['created_at'])
pageviews['created_at'] = pd.to_datetime(pageviews['created_at'])
orders['created_at'] = pd.to_datetime(orders['created_at'])
order_items['created_at'] = pd.to_datetime(order_items['created_at'])
refunds['created_at'] = pd.to_datetime(refunds['created_at'])
products['created_at'] = pd.to_datetime(products['created_at'])

8. Create Analytical Datasets

8.1. Session -> Order

In [54]:
session_order = sessions.merge(orders, on='website_session_id', how='left')

In [55]:
session_order.shape

(472871, 16)

In [56]:
session_order.head()

,website_session_id,created_at_x,user_id_x,is_repeat_session,utm_source,utm_campaign,utm_content,device_type,http_referer,order_id,created_at_y,user_id_y,primary_product_id,items_purchased,price_usd,cogs_usd
0,1,2012-03-19 08:04:16,1,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,NaN,NaT,NaN,NaN,NaN,NaN,NaN
1,2,2012-03-19 08:16:49,2,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,NaN,NaT,NaN,NaN,NaN,NaN,NaN
2,3,2012-03-19 08:26:55,3,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,NaN,NaT,NaN,NaN,NaN,NaN,NaN
3,4,2012-03-19 08:37:33,4,0,gsearch,nonbrand,g_ad_1,desktop,https://www.gsearch.com,NaN,NaT,NaN,NaN,NaN,NaN,NaN
4,5,2012-03-19 09:00:55,5,0,gsearch,nonbrand,g_ad_1,mobile,https://www.gsearch.com,NaN,NaT,NaN,NaN,NaN,NaN,NaN

8.2. Order -> Product

In [57]:
order_product = orders.merge(order_items, on='order_id', how='left').merge(products, on='product_id', how='left')

In [59]:
order_product.shape

(40025, 16)

In [61]:
order_product.head()

,order_id,created_at_x,website_session_id,user_id,primary_product_id,items_purchased,price_usd_x,cogs_usd_x,order_item_id,created_at_y,product_id,is_primary_item,price_usd_y,cogs_usd_y,created_at,product_name
0,1,2012-03-19 10:42:46,20,20,1,1,49.99,19.49,1,2012-03-19 10:42:46,1,1,49.99,19.49,2012-03-19 08:00:00,The Original Mr. Fuzzy
1,2,2012-03-19 19:27:37,104,104,1,1,49.99,19.49,2,2012-03-19 19:27:37,1,1,49.99,19.49,2012-03-19 08:00:00,The Original Mr. Fuzzy
2,3,2012-03-20 06:44:45,147,147,1,1,49.99,19.49,3,2012-03-20 06:44:45,1,1,49.99,19.49,2012-03-19 08:00:00,The Original Mr. Fuzzy
3,4,2012-03-20 09:41:45,160,160,1,1,49.99,19.49,4,2012-03-20 09:41:45,1,1,49.99,19.49,2012-03-19 08:00:00,The Original Mr. Fuzzy
4,5,2012-03-20 11:28:15,177,177,1,1,49.99,19.49,5,2012-03-20 11:28:15,1,1,49.99,19.49,2012-03-19 08:00:00,The Original Mr. Fuzzy

8.3. Order -> Refund

In [64]:
order_refund = order_items.merge(refunds, on='order_item_id', how='left')

In [65]:
order_refund.shape

(40025, 11)

In [66]:
order_refund.head()

,order_item_id,created_at_x,order_id_x,product_id,is_primary_item,price_usd,cogs_usd,order_item_refund_id,created_at_y,order_id_y,refund_amount_usd
0,1,2012-03-19 10:42:46,1,1,1,49.99,19.49,NaN,NaT,NaN,NaN
1,2,2012-03-19 19:27:37,2,1,1,49.99,19.49,NaN,NaT,NaN,NaN
2,3,2012-03-20 06:44:45,3,1,1,49.99,19.49,NaN,NaT,NaN,NaN
3,4,2012-03-20 09:41:45,4,1,1,49.99,19.49,NaN,NaT,NaN,NaN
4,5,2012-03-20 11:28:15,5,1,1,49.99,19.49,NaN,NaT,NaN,NaN